export const documents = [
  {
    id: 1,
    title: "Strona tytułowa",
    type: "Okładka",
    status: "progress",
    target: 18,
    limit: 5,
    reviewer: "Anna Kowalska",
  },
  {
    id: 2,
    title: "Spis treści",
    type: "Spis treści",
    status: "done",
    target: 29,
    limit: 24,
    reviewer: "Anna Kowalska",
  },
  {
    id: 3,
    title: "Podsumowanie",
    type: "Opis",
    status: "done",
    target: 10,
    limit: 13,
    reviewer: "Anna Kowalska",
  },
  {
    id: 4,
    title: "Podejście techniczne",
    type: "Opis",
    status: "done",
    target: 27,
    limit: 23,
    reviewer: "Jan Nowak",
  },
  {
    id: 5,
    title: "Design",
    type: "Opis",
    status: "progress",
    target: 2,
    limit: 16,
    reviewer: "Jan Nowak",
  },
  {
    id: 6,
    title: "Możliwości",
    type: "Opis",
    status: "progress",
    target: 20,
    limit: 8,
    reviewer: "Jan Nowak",
  },
  {
    id: 7,
    title: "Integracje",
    type: "Opis",
    status: "progress",
    target: 19,
    limit: 21,
    reviewer: "Jan Nowak",
  },
  {
    id: 8,
    title: "Innowacje i korzyści",
    type: "Opis",
    status: "done",
    target: 25,
    limit: 26,
    reviewer: "—",
  },
  {
    id: 9,
    title: "Przegląd rozwiązań",
    type: "Techniczny",
    status: "done",
    target: 7,
    limit: 23,
    reviewer: "—",
  },
  {
    id: 10,
    title: "Algorytmy",
    type: "Techniczny",
    status: "done",
    target: 30,
    limit: 28,
    reviewer: "—",
  },
  {
    id: 11,
    title: "Analiza rynku",
    type: "Raport",
    status: "progress",
    target: 12,
    limit: 18,
    reviewer: "Anna Kowalska",
  },
  {
    id: 12,
    title: "Wyniki badań",
    type: "Raport",
    status: "done",
    target: 15,
    limit: 20,
    reviewer: "Jan Nowak",
  },
  {
    id: 13,
    title: "Plan wdrożenia",
    type: "Opis",
    status: "progress",
    target: 22,
    limit: 24,
    reviewer: "Anna Kowalska",
  },
  {
    id: 14,
    title: "Dokumentacja API",
    type: "Techniczny",
    status: "done",
    target: 16,
    limit: 30,
    reviewer: "Jan Nowak",
  },
  {
    id: 15,
    title: "Wnioski",
    type: "Raport",
    status: "done",
    target: 8,
    limit: 12,
    reviewer: "Anna Kowalska",
  },
  {
    id: 16,
    title: "Załączniki",
    type: "Techniczny",
    status: "progress",
    target: 6,
    limit: 10,
    reviewer: "—",
  },
] as const;

export const visitorDays = Array.from({ length: 90 }, (_, index) => ({
  date: new Date(Date.UTC(2026, 3, index + 1)).toISOString().slice(0, 10),
  desktop: 80 + ((index * 67 + index * index * 13) % 280),
  mobile: 45 + ((index * 43 + index * index * 7) % 180),
}));
