import type { Company, Job, JobWithCompany } from "@/features/jobs/types";

export const companies: Company[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "brightlabs",
    name: "BrightLabs",
    summary: "Budujemy narzędzia AI dla zespołów operacyjnych.",
    description:
      "Polski software house rozwijający produkty automatyzujące pracę zespołów finansowych i operacyjnych. Łączymy badania użytkowników, modele językowe i rygor produkcyjnego oprogramowania.",
    websiteUrl: "https://example.com/brightlabs",
    location: "Warszawa",
    sizeLabel: "51–200 osób",
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "northstar-health",
    name: "Northstar Health",
    summary: "Technologia, która oddaje czas zespołom medycznym.",
    description:
      "Europejska firma healthtech upraszczająca dokumentację i koordynację opieki. Pracujemy w środowisku regulowanym, dlatego jakość i możliwość wyjaśnienia decyzji są równie ważne jak tempo.",
    websiteUrl: "https://example.com/northstar",
    location: "Kraków / zdalnie",
    sizeLabel: "201–500 osób",
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    slug: "plain-sight",
    name: "Plain Sight",
    summary: "Studio produktowe dla ambitnych zespołów B2B.",
    description:
      "Projektujemy i wdrażamy cyfrowe produkty, które rozwiązują realne problemy biznesowe. AI traktujemy jak materiał projektowy, a nie osobną kategorię produktu.",
    websiteUrl: "https://example.com/plain-sight",
    location: "Wrocław",
    sizeLabel: "11–50 osób",
  },
];

export const jobs: Job[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    slug: "ai-product-manager",
    companyId: companies[0].id,
    title: "AI Product Manager",
    summary: "Poprowadź produkt od problemu operacyjnego do mierzalnego wdrożenia AI.",
    description:
      "Szukamy osoby, która połączy discovery, analizę danych i współpracę z zespołem inżynierskim. W pierwszym kwartale wybierzesz jeden proces finansowy, zbudujesz prototyp z klientami i zdefiniujesz kryteria bezpiecznego wdrożenia.\n\nNie oczekujemy znajomości każdego modelu. Oczekujemy umiejętności stawiania hipotez, prowadzenia eksperymentów i podejmowania decyzji na podstawie zachowania użytkowników.",
    category: "lead",
    function: "product",
    remoteStatus: "hybrid",
    locations: ["Warszawa"],
    seniority: "senior",
    contract: "employment",
    salaryMin: 22000,
    salaryMax: 29000,
    salaryCurrency: "PLN",
    salaryPeriod: "month",
    salaryKind: "gross",
    publicationStatus: "published",
    publishedAt: "2026-09-28T09:00:00.000Z",
    expiryAt: "2026-11-30T23:59:59.000Z",
    verificationStatus: "employer_verified",
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    slug: "staff-ai-engineer",
    companyId: companies[1].id,
    title: "Staff AI Engineer",
    summary: "Buduj systemy wspierające dokumentację kliniczną — z ewaluacją, nie magią.",
    description:
      "Dołączysz do zespołu platformowego odpowiedzialnego za bezpieczne użycie modeli językowych. Zaprojektujesz ewaluacje, obserwowalność i mechanizmy human-in-the-loop dla funkcji używanych przez personel medyczny.\n\nNajważniejsze będą dla nas doświadczenie produkcyjne, rozumienie ograniczeń modeli oraz umiejętność współpracy z ekspertami domenowymi.",
    category: "build",
    function: "engineering",
    remoteStatus: "remote",
    locations: ["Polska"],
    seniority: "lead",
    contract: "b2b",
    salaryMin: 30000,
    salaryMax: 39000,
    salaryCurrency: "PLN",
    salaryPeriod: "month",
    salaryKind: "net",
    publicationStatus: "published",
    publishedAt: "2026-09-25T09:00:00.000Z",
    expiryAt: "2026-12-15T23:59:59.000Z",
    verificationStatus: "editorial",
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    slug: "senior-product-designer-ai",
    companyId: companies[2].id,
    title: "Senior Product Designer — AI",
    summary: "Projektuj doświadczenia, w których użytkownik rozumie i kontroluje działanie AI.",
    description:
      "Będziesz prowadzić projekty od badań po wdrożenie, pracując bezpośrednio z klientami B2B. Szukamy osoby, która umie prototypować zachowanie systemów AI, projektować momenty kontroli i testować z realnymi użytkownikami.\n\nPortfolio powinno pokazywać tok rozumowania, kompromisy i efekt, nie tylko końcowe ekrany.",
    category: "apply",
    function: "design",
    remoteStatus: "hybrid",
    locations: ["Wrocław", "Warszawa"],
    seniority: "senior",
    contract: "b2b",
    salaryMin: 18000,
    salaryMax: 24000,
    salaryCurrency: "PLN",
    salaryPeriod: "month",
    salaryKind: "net",
    publicationStatus: "published",
    publishedAt: "2026-09-20T09:00:00.000Z",
    expiryAt: "2026-11-20T23:59:59.000Z",
    verificationStatus: "employer_verified",
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    slug: "ai-operations-specialist",
    companyId: companies[0].id,
    title: "AI Operations Specialist",
    summary: "Automatyzuj powtarzalne procesy i ucz zespół bezpiecznej pracy z AI.",
    description:
      "Zmapujesz procesy w finansach i obsłudze klienta, zbudujesz małe automatyzacje i będziesz mierzyć ich jakość. To rola dla osoby, która potrafi łączyć narzędzia no-code, analizę danych i uważność na potrzeby ludzi.\n\nWażniejsza od liczby certyfikatów jest umiejętność pokazania wdrożenia oraz jego mierzalnego efektu.",
    category: "apply",
    function: "operations",
    remoteStatus: "onsite",
    locations: ["Warszawa"],
    seniority: "mid",
    contract: "employment",
    salaryMin: 11000,
    salaryMax: 16000,
    salaryCurrency: "PLN",
    salaryPeriod: "month",
    salaryKind: "gross",
    publicationStatus: "published",
    publishedAt: "2026-09-16T09:00:00.000Z",
    expiryAt: "2026-11-16T23:59:59.000Z",
    verificationStatus: "unverified",
  },
  {
    id: "20000000-0000-4000-8000-000000000005",
    slug: "growth-lead-ai-products",
    companyId: companies[1].id,
    title: "Growth Lead — AI Products",
    summary: "Znajdź powtarzalny sposób docierania do zespołów medycznych.",
    description:
      "Poprowadzisz eksperymenty wzrostowe dla nowej linii produktów. Będziesz współpracować z produktem, sprzedażą i compliance, aby budować pętle uczenia zamiast kampanii oderwanych od doświadczenia użytkownika.\n\nSzukamy osoby, która umie używać AI do przyspieszenia pracy, ale potrafi też rozpoznać, kiedy automatyzacja obniża jakość sygnału.",
    category: "lead",
    function: "marketing",
    remoteStatus: "remote",
    locations: ["Europa"],
    seniority: "lead",
    contract: "employment",
    salaryMin: 65000,
    salaryMax: 82000,
    salaryCurrency: "EUR",
    salaryPeriod: "year",
    salaryKind: "gross",
    publicationStatus: "published",
    publishedAt: "2026-09-10T09:00:00.000Z",
    expiryAt: "2026-11-10T23:59:59.000Z",
    verificationStatus: "editorial",
  },
  {
    id: "20000000-0000-4000-8000-000000000006",
    slug: "machine-learning-engineer",
    companyId: companies[2].id,
    title: "Machine Learning Engineer",
    summary: "Wdrażaj małe, dobrze zmierzone funkcje ML w produktach klientów.",
    description:
      "Będziesz pracować w małym zespole nad prototypami, pipeline'ami danych i ewaluacją. Projekty szybko przechodzą od eksperymentu do produkcji, dlatego liczy się odpowiedzialność za cały cykl życia rozwiązania.\n\nDobrze odnajdzie się tu osoba z solidnym Pythonem i doświadczeniem w pracy z zespołem produktowym.",
    category: "build",
    function: "data",
    remoteStatus: "hybrid",
    locations: ["Wrocław"],
    seniority: "mid",
    contract: "b2b",
    salaryMin: 19000,
    salaryMax: 26000,
    salaryCurrency: "PLN",
    salaryPeriod: "month",
    salaryKind: "net",
    publicationStatus: "published",
    publishedAt: "2026-09-08T09:00:00.000Z",
    expiryAt: "2026-11-08T23:59:59.000Z",
    verificationStatus: "editorial",
  },
];

export function joinJobsWithCompanies(sourceJobs = jobs): JobWithCompany[] {
  return sourceJobs.flatMap((job) => {
    const company = companies.find((entry) => entry.id === job.companyId);
    return company ? [{ ...job, company }] : [];
  });
}
